- name: tar zxf libpri-1.4.12 openvox_dahdi
  unarchive:
    src: '{{ item }}'
    dest: /tmp/btg
  with_items:
    - libpri-1.4.12.tar.gz
    - openvox_dahdi-linux-complete-2.6.1+2.6.1.tar.gz
- name: make clean
  make:
    chdir: '/tmp/btg/{{ item }}'
    target: clean
  with_items:
    - libpri-1.4.12
    - dahdi-linux-complete-2.6.1+2.6.1
- name: make
  make:
    chdir: /tmp/btg/libpri-1.4.12
- name: make install
  make:
    chdir: /tmp/btg/libpri-1.4.12
    target: install
- name: make
  make:
    chdir: /tmp/btg/dahdi-linux-complete-2.6.1+2.6.1
    target: '{{ item }}'
  with_items:
    - install
    - config
- name: mv dahdi dahdi.conf
  shell:  mv /etc/modprobe.d/dahdi /etc/modprobe.d/dahdi.conf
  ignore_errors: True
- name: mv dahdi.blacklist dahdi.conf
  shell: mv /etc/modprobe.d/dahdi.blacklist /etc/modprobe.d/dahdi.blacklist.conf
  ignore_errors: True
- name: restart dahdi
  shell: /etc/init.d/dahdi restart
  ignore_errors: True
- name: touch dahdi_conf
  shell: dahdi_genconf
  ignore_errors: True
- name: dahdi_conf feedback
  shell: dahdi_cfg -vvvvv
  ignore_errors: True
- name: /etc/dahdi/system.conf
  replace:
    path: /etc/dahdi/system.conf
    regexp: '{{ item.attr }}'
    replace: '{{ item.value }}'
  with_items:
    - { attr: 'hdb3,crc4', value: 'hdb3' }
    - { attr: 'echocanceller', value: '#echocanceller' }
- name: restart dahdi
  shell: /etc/init.d/dahdi restart
  ignore_errors: True
