- name: 解压node-v0.12
  unarchive:
    src: node-v0.12.18-linux-x64.tar.xz
    dest: /opt
- name: 解压node-v6.14
  unarchive:
    src: node-v6.14.4-linux-x64.tar.xz
    dest: /opt
- name: 创建软连接
  file:
    src: '/opt/{{ item.src }}'
    dest: '/opt/{{ item.dest }}'
    state: link
  with_items:
  - { src: 'node-v0.12.18-linux-x64', dest: 'node' }
  - { src: 'node-v6.14.4-linux-x64', dest: 'node6.14' }
- name: 为node-v6设置环境变量
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/opt/node6.14/bin'
