---
- name: 安装nss-pam-ldapd和其它依赖项
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - libselinux-python
    - nss-pam-ldapd

- name: 配置SSH公钥-jerry
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: 修改authconfig的python版本
  lineinfile:
    path: /usr/share/authconfig/authconfig.py
    regexp: '^#!/usr/bin/python'
    line: '#!/usr/bin/python2.6'
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: 配置LDAP客户端
  shell: |
    authconfig --enableshadow \
    --disablesssd \
    --disablesssdauth \
    --enableldap \
    --enableldapauth \
    --ldapserver={{ ldap_server }} \
    --ldapbasedn="{{ basedn }}" \
    {% if tls  %}
    --enableldaptls \
    {% endif %}
    --enablecache \
    --enablelocauthorize \
    --enablemkhomedir \
    --updateall
  args:
    executable: /bin/bash

- name: 配置sudo-ldap.conf
  blockinfile:
    path: /etc/sudo-ldap.conf
    backup: yes
    block: |
      uri {{ ldap_server }}
      sudoers_base {{ sudoers_base }}
    marker: "# sudo-ldap 配置信息 {mark}"

- name: 配置命名服务交换文件
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^sudoers'
    line: 'sudoers: files ldap'

- name: 确保nslcd服务在运行中-centos6
  service:
    name: nslcd
    enabled: yes
    state: started
  when:
     - ansible_distribution == "CentOS"
     - ansible_distribution_major_version == "6"

- name: 确保nslcd服务在运行-centos7
  systemd:
    name: nslcd
    enabled: yes
    state: started
  when:
     - ansible_distribution == "CentOS"
     - ansible_distribution_major_version == "7"
